

# =======================================
# = JWT Configuration
# =======================================
jwtSecret: jwtSecretKey
jwtExpiration: 86400 # -> 1 day


# =======================================
# = Server Configuration
# =======================================
server:
  port: 22505

# =======================================
# = Spring Configuration
# =======================================
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/chatapp_lobby?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  application:
    name: lobby-service

# =======================================
# = Eureka Configuration
# =======================================
eureka:
  client:
    service-url:
      defaultZone: http://localhost:22500/eureka
  instance:
    prefer-ip-address: false

